import type { StarlightSidebarTopicsUserConfig } from "starlight-sidebar-topics";
import { readdirSync, statSync } from "fs";


const contentRoot = "src/content/docs/"
// return item with autogenerated if is directory, else return simple item with path
export function getItems(dir: string) {
  const entries = readdirSync(dir);
  return entries.map((entry) => {
    const fullPath = `${dir}/${entry}`;
    if (statSync(fullPath).isDirectory()) {
      return { label: entry, autogenerate: { directory: fullPath.replace(contentRoot, "") } };
    } else if ((entry.endsWith(".md") || entry.endsWith(".mdx")) && !entry.includes("index")) {
        // remove contentRoot and file extension (md, mdx)
        return fullPath.replace(contentRoot, "").replace(/\.mdx?$/, "");
       }
    }).filter(v=> v !== undefined)
  }

export let sidebar: StarlightSidebarTopicsUserConfig = [
  {
    label: "Linux",
    id: "linux",
    link: "/notes/linux/",
    items: getItems(`${contentRoot}notes/linux`),
  },
  {
    label: "Redis",
    link: "/notes/redis/",
    id: "redis",
    items: getItems(`${contentRoot}notes/redis`),
  },
];




export let options = {
  exclude: ["/blog", "/blog/**/*"],
  // 自動將目錄下沒被列在 sidebar 的檔案加入 topics
  // 但不會自動出現在側邊欄上，bad
  topics: {
    redis: ["/notes/redis/"],
    linux: ["/notes/linux/"],
  },
};
